### ISSUE TITLE
Design in Future - Charts are repeating on mobile

### ISSUE THREAD

**Issue by mmcvicar** [jenyuan0/fod17-results#11]
The charts under "Skills - Near Term:" and "Skills - Further Out:" seem to repeat on mobile:

![img_3245](https://user-images.githubusercontent.com/1929795/34083887-916fb7c6-e345-11e7-985a-9fee877fea53.PNG)

**Comment by jenyuan0** [comment]
Fixed! "future" or "near" tags (subtitle) needs to be added to the back-end.
