### ISSUE TITLE
Update Money Chart colors

### ISSUE THREAD

**Issue by mmcvicar** [jenyuan0/fod17-results#14]
Change chart to dark navy HEX: #372ea9

Here's the new chart SVG if that's helpful:
https://www.dropbox.com/s/u6zxgmjzoujc953/money-chart.svg?dl=0

<img width="1053" alt="screen shot 2017-12-17 at 8 45 37 pm" src="https://user-images.githubusercontent.com/1929795/34087972-7530ba2c-e374-11e7-9021-8ca4505844e7.png">

**Comment by jenyuan0** [comment]
Can you pass me graph for mobile too?

@mmcvicar

**Comment by mmcvicar** [comment]
Yes! Here it is. Make sure to update the text and line that are still in the old color:
https://www.dropbox.com/s/3vtklzjkragnqnt/money-chart-mobile.svg?dl=0
