### ISSUE TITLE
Embed Slideshare

### ISSUE THREAD

**Issue by gitalbert** [jenyuan0/fod17-results#28]
LINK: 
https://www.slideshare.net/AlbertLee64/future-of-design-in-startups-survey-2017-84415665

WORDPRESS SHORTCODE:

[slideshare id=84415665&doc=neafodpresentation2017draft121817newformat-171219031920]

EMBED:

<iframe src="//www.slideshare.net/slideshow/embed_code/key/8tSbm2jTNKcIka" width="595" height="485" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe> <div style="margin-bottom:5px"> <strong> <a href="//www.slideshare.net/AlbertLee64/future-of-design-in-startups-survey-2017-84415665" title="Future of Design in Start-Ups Survey 2017" target="_blank">Future of Design in Start-Ups Survey 2017</a> </strong> from <strong><a href="https://www.slideshare.net/AlbertLee64" target="_blank">Albert Lee</a></strong> </div>

**Comment by jenyuan0** [comment]
@gitalbert can you check the privacy settings? It's showing up as private content.

**Comment by jenyuan0** [comment]
Maybe there is additionally settings for when the sliders are embedded?
