### ISSUE TITLE
Add byline to Quotes

### ISSUE THREAD

**Issue by mmcvicar** [jenyuan0/fod17-results#7]
Sorry, this was in the final design but I failed to point out. We need to add a by-line right under the logos in the quote section. Should be 1 line and size 12px font. 10px padding under the logo.

![image](https://user-images.githubusercontent.com/1929795/34083623-62f6dde2-e341-11e7-83d0-080db606884f.png)

**Comment by jenyuan0** [comment]
Added! Note that this shouldn't be too long that it spans through the dots.
